<?php

namespace GkhBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ElectronicTreatmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElectronicTreatmentRepository extends EntityRepository
{
}
