<?php

namespace GkhBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PersonalAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalAccountRepository extends EntityRepository
{
}
