<?php

namespace GkhBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRequestRepository extends EntityRepository
{
}
