gkh:
    resource: "@GkhBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

users:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"